Simplify reverse tuple iteration
fnc12/sqlite_orm pull request #1161
Opened 2023-03-19 13:28 UTC by vittorioromeo

Should help a bit with #1160. Would also be nice to see how it interacts with #1055

2023-03-19 13:33 UTC, fnc12 commented
@vittorioromeo thank you for this PR. Please resolve the conflicts to be able to run CI tests

2023-03-19 13:38 UTC, vittorioromeo commented
> @vittorioromeo thank you for this PR. Please resolve the conflicts to be able to run CI tests

Should be fine now :)

2023-03-19 13:40 UTC, fnc12 commented
@vittorioromeo did you test compilation time with your branch? I am actually not sure whether reverse tuple iteration is used anywhere so I am not sure whether your fix will make much effort

2023-03-19 13:44 UTC, vittorioromeo commented
> @vittorioromeo did you test compilation time with your branch? I am actually not sure whether reverse tuple iteration is used anywhere so I am not sure whether your fix will make much effort

I saw a very small improvement of average 24ms per instantiation of `iterate_tuple` from 28ms, but hard to tell if it's impactful in any way. There are a few calls to `iterate_tuple<true>` in the codebase. Regardless, I think that the PR is an improvement overall because of the removal of unnecessary code.

2023-03-19 21:31 UTC, trueqbit commented
This is awesome C++! Thanks @vittorioromeo for thinking along.

I doubt you will see any overall improvement in compilation times.
But it simplifies the code, and that was what I was originally looking for when I updated the tuple iteration but couldn't find it!

By the way, there is good reading about this fold expression trickery:
* https://www.foonathan.net/2020/05/fold-tricks
* https://quuxplusone.github.io/blog/2020/05/07/assignment-operator-fold-expression/

2023-03-19 21:31 UTC, trueqbit requested changes

2023-03-19 21:31 UTC, trueqbit commented on dev/functional/index_sequence_util.h
Could you please also remove
```c++
#ifdef SQLITE_ORM_RELAXED_CONSTEXPR_SUPPORTED
#include <array>
#endif
```
from the top of the header?

2023-03-19 21:31 UTC, trueqbit commented on dev/tuple_helper/tuple_iteration.h
> +                int sink;
Please put a comment above similar to:
`// nifty fold expression trick: make use of guaranteed right-to-left evaluation order when folding over operator=`.

Even seasoned C++ programmers will find it helpful :) - Even I had to try it out and find out about it.

2023-03-19 22:09 UTC, trueqbit commented on dev/functional/index_sequence_util.h
BTW, we might implement `first_index_sequence_value()` as follows. What do you think?

```c++
template<size_t... Idx>
SQLITE_ORM_CONSTEVAL size_t first_index_sequence_value(std::index_sequence<Idx...>) {
    static_assert(sizeof...(Idx) > 0);
    size_t result;
    ((result = Idx, true) || ...);
    return result;
}
```

2023-03-20 00:51 UTC, vittorioromeo commented on dev/functional/index_sequence_util.h
Compared to the current implementation, I'm not sure it's going to be faster. I would recommend a benchmark on https://www.build-bench.com/

2023-03-20 11:19 UTC, trueqbit approved these changes

2023-03-20 11:52 UTC, fnc12 approved these changes

2023-03-20 11:52 UTC, merged

2023-03-20 11:52 UTC, fnc12 commented
@vittorioromeo thanks!