Extract sqlite3 step
fnc12/sqlite_orm pull request #603
Opened 2020-10-06 02:50 UTC by undisputed-seraphim

First commit: Update the version, which hasn't been updated since 1.3.0

Second commit: Extract out `sqlite3_step`, in order to prepare for possible implementations of the retry logic.
This commit gathers all `sqlite3_step` in other files into `storage_base.h` by introducing `perform_step`.

Additionally, this commit removes redundant functions `begin_transaction`, `commit`, and `rollback` in storage_base.h which are just more wrappers around `sqlite3_step`.

2020-10-06 06:56 UTC, fnc12 commented
Move `perform_step` to `storage_impl_base` and call `this->impl.perform_step` inside `storage` and `storage_base` and replace all `sqlite3_step` inside `storage_impl.h` with `perform_step`. Also there is one `sqlite3_step` call inside `iterator.h` file. Probably it is better to move `perform_step` to a different file like `utils.h`. Then we will move it again if it is required. Thanks

2020-10-06 06:58 UTC, fnc12 commented
Also you have two builds failed 
https://ci.appveyor.com/project/fnc12/sqlite-orm/builds/35586799/job/i80fup4o4qejqre4
https://ci.appveyor.com/project/fnc12/sqlite-orm/builds/35586799/job/75hmsxnmmqpd2asu

2020-10-06 11:28 UTC, undisputed-seraphim commented
Ah I just noticed that `storage_base.h` does not `#include "storage_impl.h"` . Should it? `storage_base.h` can't access `perform_step` otherwise.

Since `perform_step` can be a static function (it doesn't depend on the state of any objects except for its parameters) I suppose we can put it in an existing utility header.

2020-10-06 21:49 UTC, fnc12 commented
>Ah I just noticed that storage_base.h does not #include "storage_impl.h"

Everything is fine here. `storage_impl` cannot include `storage_base` cause otherwise circular includes will occur.

> Since perform_step can be a static function (it doesn't depend on the state of any objects except for its parameters) I suppose we can put it in an existing utility header.

Yes this is the best way to make it work. Please do it this way. Thanks

2020-10-08 07:51 UTC, undisputed-seraphim commented
I have made the requested changes. I couldn't find a suitable existing utility header so I created a new one, `util.h`. If you have another suggestion please let me know :)

2020-10-11 11:01 UTC, fnc12 requested changes
Please fix conflicts and react to two comments I added. Thanks

2020-10-12 05:58 UTC, undisputed-seraphim commented on dev/util.h
> +#include <string>  //  std::string
Removed. I think it was included when I was testing some code.

2020-10-12 05:58 UTC, undisputed-seraphim commented on dev/util.h
> +#include <system_error>  //  std::system_error, std::error_code, std::make_error_code
Done.

2020-10-13 10:02 UTC, fnc12 approved these changes

2020-10-13 10:29 UTC, merged