Fix warning
fnc12/sqlite_orm pull request #698
Opened 2021-04-15 20:23 UTC by denzor200

2021-04-16 03:26 UTC, fnc12 requested changes

2021-04-16 03:26 UTC, fnc12 commented on dev/table_name_collector.h
> +            void operator()(const column_pointer<T, F> &) const {
these fixes do not exist in `sqlite_orm.h`. Please rerun `amalgamate.py` script and push it

2021-04-24 15:59 UTC, fnc12 commented
something wrong with format checking. We need understand why amalgamate breaks some formatting results. Anyway this PR is ok so I am merging it. @denzor200 thanks

2021-04-24 15:59 UTC, merged

2021-04-24 16:03 UTC, juandent commented
Hi!

 

I downloaded dev branch but don’t know where is the code for SQL:

 

select fkey_INSResponse = 1, number from Invoices

 

Please give a small example

 

Regards,

Juan Dent

 

From: Yevgeniy Zakharov ***@***.***> 
Sent: Saturday, April 24, 2021 10:00 AM
To: fnc12/sqlite_orm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [fnc12/sqlite_orm] Fix warning (#698)

 

Merged #698 <https://github.com/fnc12/sqlite_orm/pull/698>  into dev.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://github.com/fnc12/sqlite_orm/pull/698#event-4640101091> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABI6OFLHIXMFFZH2QWM3ZHLTKLTHPANCNFSM43AGB7FQ> .  <https://github.com/notifications/beacon/ABI6OFJKPMQMLDUXFYYLMHDTKLTHPA5CNFSM43AGB7F2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGPAAAAAAIUSJJOG.gif>