Pointer passing examples
fnc12/sqlite_orm pull request #844
Opened 2021-11-20 21:57 UTC by trueqbit

Solidified pointer-passing interface.

- Added example for statically and dynamically bound objects.
- Added unit tests for dynamically allocated objects.
- Fixed UB and refactored obtaining 'xDestroy' function.
  * there's now a safe way of obtaining a 'xDestroy' function from a deleter and a pointer.
  * the previous approach was inherently UB on some platforms (function pointers can't be aliased and then called through that alias, unless the argument/return type representation is the same).
  * implemented understandable constraints which 'deleter' can be used for obtaining a 'xDestroy' function.
  * stateless deleters are possible, as well as objects yielding a 'xDestroy' function pointer.

2021-11-22 12:41 UTC, fnc12 commented
@trueqbit when I should make a review? [Now or later](https://www.youtube.com/watch?v=La8_Q6YBTSs&ab_channel=DylanMatthew)?

2021-11-22 14:05 UTC, trueqbit commented
> @trueqbit when I should make a review?

Wait still, please. I am still investigating matters in regard to pointer-to-object lifetime!

2021-11-22 22:47 UTC, trueqbit commented
@fnc12 F.I.N.A.L.L.Y.
woah. C++20 builds are slow!

2021-11-23 09:30 UTC, fnc12 commented
@trueqbit so is it time to review or no?

2021-11-23 14:45 UTC, trueqbit commented
@fnc12 Yes, it's time for review - sorry I had those ideas overnight, which made it into the last commit.

I am inclined to remove the `template<const char* T> bindable_pointer()`> overloads. It's probably better to change later if needed rather than over-engineer now.

2021-11-23 20:17 UTC, fnc12 commented
@trueqbit please review my comment at `examples/pointer_passing_interface.cpp` at line 207

2021-11-23 21:19 UTC, trueqbit commented
@fnc12 Where's your comment? I presume it's about the commented out order-by clause - I couldn't get it to work initially. Seems like I misunderstood multi_order_by.

Do you have other comments before I push again, and trigger another test build?

In case you didn't see my previous question:
> I am inclined to remove the `template<const char* T> bindable_pointer()`> overloads. It's probably better to change later if needed rather than over-engineer now.

I think you agree, but I'd like to make sure before I remove it...

2021-11-23 22:35 UTC, fnc12 commented
> I am inclined to remove the template<const char* T> bindable_pointer()> overloads. It's probably better to change later if needed rather than over-engineer now.

Yes I agree.

Yes my comment is about multy_order_by. What result you get if you uncomment it? Let's fix it or remove it. Commented code in examples is not the best idea.

Please push new code at any time. Thank you for your job. It is awesome.

2021-11-24 00:32 UTC, trueqbit commented
The wrong sort order is unrelated to this PR or the pointer-passing feature. I will come up with another bug ticket in regard to this.
Otherwise the PR is good to go once the new commits yield a green test build.

2021-11-24 12:40 UTC, fnc12 commented
@trueqbit ok. Please review comment at line 698 in `tests/tests2.cpp`

2021-11-24 18:00 UTC, fnc12 commented
> I reckon it would be helpful if you commented directly at the line in the 'files' view

This is what I do. Thanks

2021-11-24 18:02 UTC, fnc12 commented
<img width="910" alt="Снимок экрана 2021-11-24 в 21 02 16" src="https://user-images.githubusercontent.com/6009640/143291481-3d811fec-84bb-4606-9f18-15886a11678b.png">

2021-11-24 18:49 UTC, trueqbit commented
> > I reckon it would be helpful if you commented directly at the line in the 'files' view
> 
> This is what I do. Thanks

How dare I to ask you :) I swear that I didn't see anything; also now I don't see any comments or conversation :(

2021-11-24 18:50 UTC, fnc12 commented
Strange. Probably I must make a review finish for you to see my comments

2021-11-24 18:50 UTC, fnc12 requested changes

2021-11-24 18:51 UTC, fnc12 commented
check it out now please

2021-11-24 19:09 UTC, trueqbit commented on examples/pointer_passing_interface.cpp
> +            multi_order_by(!c(&Result::errorValue), &Result::errorCategory, &Result::errorValue, &Result::id)*/);
Corrected in FireDaemon/sqlite_orm@a2bb4fcfc48b.

No, it's not a valid expression. I believe it should - it is valid sql and makes sense when columns are falsy [null or 0]. But it requires expression_t to be negatable.

2021-11-24 19:10 UTC, trueqbit commented on tests/tests2.cpp
> +            {
I thought I leave the brackets for the sake of resemblance to the previous sections.
No objection, though :)
Corrected in commit FireDaemon/sqlite_orm@2547bfe.

2021-11-24 19:15 UTC, fnc12 commented
please add `tests/statement_serializator_tests/bound_pointer.cpp` to CMakeLists.txt

2021-11-24 22:09 UTC, fnc12 approved these changes

2021-11-24 22:47 UTC, merged

2021-11-24 22:47 UTC, fnc12 commented
@trueqbit thanks! This is a great feature!